name: linalg

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: echo "Hello, World!"
