name: linalg

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  unit-tests:
    name: unit-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: Run unit tests
      run: cargo test --lib

  integration-tests:
    name: integration-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - name: Run integration tests
      run: cargo test --test '*'
